name: Build and publish manually

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Image version"
        required: true

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Build image
        run: docker build -t steiner .
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600
      - name: Tag image
        run: docker tag steiner registry.digitalocean.com/steiner/steiner:${{github.event.inputs.version }}
      - name: Push image to DO Container Registry
        run: docker push registry.digitalocean.com/steiner/steiner:${{ github.event.inputs.version }}
      - name: Create deployment
        run: doctl apps create-deployment steiner --wait
